color = input("Enter a color: ")
plural_noun = input("Enter a plural noun: ")
celeb = input("Enter a celeb name: ")
print(f"Roses are {color})
print(f"{plural_noun} are blue")
print(f"I love {celeb}")